coverage:
 status:
  project:
   default:
    target: 80%
    threshold: 1%
  patch:
   default:
    target: 80%
    threshold: 1%
    patch:
     - "src/**/*.ts"
     - "!src/**/*.d.ts"

comment:
 layout: "reach, diff, flags, files"
 behavior: once
 require_changes: true
 show_carryforward_flags: false
 branches:
  - main
  - qa

github_checks:
 annotations: true
 branches:
  - main
  - qa

flags:
  core:
    paths:
      - "src/index.ts"
    carryforward: false
  hooks:
    paths:
      - "src/hooks/**"
  stores:
    paths:
      - "src/stores/**"
  utils:
    paths:
      - "src/utils/**"
ignore:
 - "**/*.test.ts"
 - "**/*.d.ts"
