name: Codesandbox CI Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  codesandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Codesandbox CI
        uses: codesandbox/codesandbox-ci@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
