name: Setup Labels
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  setup-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Create Missing Labels
        uses: actions/github-script@v7
        with:
          script: |
            // Define all possible labels with colors and descriptions
            const allLabels = [
              {
                name: 'documentation',
                color: '0075ca',
                description: 'Changes to documentation files'
              },
              {
                name: 'coding',
                color: '0e8a16',
                description: 'Changes to source code files'
              },
              {
                name: 'tests',
                color: 'ff9e1e',
                description: 'Changes to test files'
              },
              {
                name: 'dependencies',
                color: 'd93f0b',
                description: 'Changes to dependency files'
              },
              {
                name: 'configuration',
                color: '5319e7',
                description: 'Changes to configuration files'
              },
              {
                name: 'workflow',
                color: 'bfdadc',
                description: 'Changes to CI/CD workflows'
              }
            ];

            // Get existing labels
            const existingLabels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });

            const existingLabelNames = existingLabels.data.map(label => label.name);

            // Create missing labels
            for (const label of allLabels) {
              if (!existingLabelNames.includes(label.name)) {
                try {
                  await github.rest.issues.createLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ...label
                  });
                  console.log(`Created label: ${label.name}`);
                } catch (error) {
                  console.error(`Failed to create label ${label.name}:`, error.message);
                }
              } else {
                console.log(`Label "${label.name}" already exists.`);
              }
            }
